spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass_local_user
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  batch: #TODO
    jdbc:
      initialize-schema: always
    job.names: ${job.name:NONE}


kakaotalk:
  host: https://kapi.kakao.com
  token: YOUR_ACCESS_TOKEN